"""Initial migration

Revision ID: 1d24abc78ade
Revises: 
Create Date: 2026-07-03 17:50:54.132518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d24abc78ade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_items', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('pedido_items', 'precio_unitario',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(None, 'pedido_items', type_='foreignkey')
    op.create_foreign_key(None, 'pedido_items', 'pedidos', ['pedido_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pedidos', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('pedidos', 'fecha_pedido',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('pedidos', 'monto_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('pedidos', 'fecha_actualizacion',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('productos', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('productos', 'precio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('productos', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('productos', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('productos', 'precio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('productos', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('pedidos', 'fecha_actualizacion',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('pedidos', 'monto_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('pedidos', 'fecha_pedido',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("(datetime('now', 'localtime'))"))
    op.alter_column('pedidos', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'pedido_items', type_='foreignkey')
    op.create_foreign_key(None, 'pedido_items', 'pedidos', ['pedido_id'], ['id'])
    op.alter_column('pedido_items', 'precio_unitario',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('pedido_items', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
