"""Add repartidor to Pedido

Revision ID: 4c2d391250fb
Revises: 1d24abc78ade
Create Date: 2026-07-06 12:08:07.164499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2d391250fb'
down_revision: Union[str, None] = '1d24abc78ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_items', 'precio_unitario',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('pedidos', sa.Column('repartidor', sa.Text(), nullable=True))
    op.alter_column('pedidos', 'monto_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('productos', 'precio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'precio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('pedidos', 'monto_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('pedidos', 'repartidor')
    op.alter_column('pedido_items', 'precio_unitario',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
